name: Build and push Docker image on master change

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t skabold/devops-nextjs:latest ../devops-nextjs
          docker push skabold/devops-nextjs:latest
